# Site settings
title: TechnicallyJoe
description: 'Windows Systems Engineer with a flair for the DevOps initiative and a love for automating everything'
url: 'https://technicallyjoe.netlify.com/'
baseurl: ''
google_analytics: 'UA-105267729-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'TechnicallyJoe'
#  email: josh@joshgerdes.com
  github_username:  technicallyjoe
  linkedin_username:  jonathanoestrup

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
